
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '5237B458A5A8BF52B73BDD3AEA840405'
    
_lr_action_items = {'COUNTER':([2,5,6,],[10,12,13,]),'STOP':([0,3,4,7,8,9,10,13,15,19,21,],[4,4,-3,-6,-5,-4,-9,-8,4,4,-7,]),'INC':([0,3,4,7,8,9,10,13,15,19,21,],[6,6,-3,-6,-5,-4,-9,-8,6,6,-7,]),'ZERO':([0,3,4,7,8,9,10,13,15,19,21,],[5,5,-3,-6,-5,-4,-9,-8,5,5,-7,]),'QUEST':([12,],[14,]),'COLON':([17,],[18,]),'CLOSE':([4,7,8,9,10,13,16,20,21,],[-3,-6,-5,-4,-9,-8,17,21,-7,]),'DEC':([0,3,4,7,8,9,10,13,15,19,21,],[2,2,-3,-6,-5,-4,-9,-8,2,2,-7,]),'OPEN':([14,18,],[15,19,]),'$end':([0,1,3,4,7,8,9,10,11,13,21,],[-1,0,-1,-3,-6,-5,-4,-9,-2,-8,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'pr':([0,3,],[1,11,]),'zero':([0,3,15,19,],[7,7,7,7,]),'dec':([0,3,15,19,],[8,8,8,8,]),'inc':([0,3,15,19,],[9,9,9,9,]),'instr':([0,3,15,19,],[3,3,16,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> pr","S'",1,None,None,None),
  ('pr -> <empty>','pr',0,'p_pr','parser_3cm.py',25),
  ('pr -> instr pr','pr',2,'p_pr','parser_3cm.py',26),
  ('instr -> STOP','instr',1,'p_instr','parser_3cm.py',34),
  ('instr -> inc','instr',1,'p_instr','parser_3cm.py',35),
  ('instr -> dec','instr',1,'p_instr','parser_3cm.py',36),
  ('instr -> zero','instr',1,'p_instr','parser_3cm.py',37),
  ('zero -> ZERO COUNTER QUEST OPEN instr CLOSE COLON OPEN instr CLOSE','zero',10,'p_zero','parser_3cm.py',45),
  ('inc -> INC COUNTER','inc',2,'p_inc','parser_3cm.py',50),
  ('dec -> DEC COUNTER','dec',2,'p_dec','parser_3cm.py',55),
]
